---
- name: AWS EFS
  become: yes
  block:
    - name: Allow release info changes
      command: apt-get update# --allow-releaseinfo-change
    - name: Update repositories cache
      apt:
        update_cache: yes
    - name: Ensure NFS is installed
      package:
        name:
          - nfs-common
          #- autofs
          - rpcbind
        state:
          present
    - name: Ensure rpcbind service is running
      service: name=rpcbind state=started enabled=yes
    - name: Create mount point
      file: path='{{ aws_efs_path }}' state=directory owner='{{ aws_efs_owner }}' group='{{ aws_efs_group }}'
    - name: Get current AZ from AWS
      uri:
        url: http://169.254.169.254/latest/meta-data/placement/availability-zone
        return_content: yes
      register: aws_current_az
    - name: Ensure EFS volume is mounted
      mount:
        name: "{{ aws_efs_path }}"
        src: "{{ aws_current_az.content }}.{{ aws_efs_id }}.efs.{{ aws_efs_region }}.amazonaws.com:/"
        fstype: nfs4
        opts: nfsvers=4.1
        state: mounted
    - name: Ensure permissions
      file:
        path: '{{ aws_efs_path }}'
        owner: '{{ aws_efs_owner }}'
        group: '{{ aws_efs_group }}'
        mode: '{{ aws_efs_permissions }}'
